#!/bin/bash
# Copyright (c) 2000-2012 Synology Inc. All rights reserved.

LANG=C; export LANG
LC_ALL=C; export LC_ALL

case ${MakeClean} in
    [Yy][Ee][Ss])
        /bin/rm /usr/local/lib/libev.*
	/bin/rm /usr/local/include/ev++.h /usr/local/include/ev.h /usr/local/include/event.h
        ;;
esac

case ${CleanOnly} in
    [Yy][Ee][Ss])
        return
        ;;
esac

/bin/sh ./autogen.sh

# LDFLAGS -s for stripping
env CC="${CC}" CXX="${CXX}" LD="${LD}" AR=${AR} STRIP=${STRIP} RANLIB=${RANLIB} NM=${NM} \
    CFLAGS="${CFLAGS}" CXXFLAGS="$CXXFLAGS $CFLAGS" \
    LDFLAGS="${LDFLAGS} -s" \
    ./configure ${ConfigOpt} \
    --prefix=/usr/local

#    --disable-shared \

make ${MAKE_FLAGS}

make install
