#!/bin/bash
# Copyright (c) 2000-2012 Synology Inc. All rights reserved.

LANG=C; export LANG
LC_ALL=C; export LC_ALL

case ${MakeClean} in
    [Yy][Ee][Ss])
        make clean
        /bin/rm /usr/local/bin/simple-obfs.*
        ;;
esac

case ${CleanOnly} in
    [Yy][Ee][Ss])
        return
        ;;
esac

./autogen.sh

# LDFLAGS -s for stripping
env CC="${CC}" CXX="${CXX}" LD="${LD}" AR=${AR} STRIP=${STRIP} RANLIB=${RANLIB} NM=${NM} \
    CFLAGS="${CFLAGS}" CXXFLAGS="$CXXFLAGS $CFLAGS" \
    LDFLAGS="${LDFLAGS} -s" \
    ./configure --disable-documentation --with-ev=/usr/local ${ConfigOpt} \
    --prefix=/usr/local

#    --disable-shared \

make ${MAKE_FLAGS}

make install
