#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

PKG_NAME=shadowsocks-libev
INST_DIR=/tmp/_${PKG_NAME}

LANG=C; export LANG
LC_ALL=C; export LC_ALL

case ${MakeClean} in
    [Yy][Ee][Ss])
        make clean
        ;;
esac

# -s in LDFLAGS for stripping
env CC="${CC}" CXX="${CXX}" LD="${LD}" AR=${AR} STRIP=${STRIP} RANLIB=${RANLIB} NM=${NM} \
    CFLAGS="${CFLAGS}" CXXFLAGS="$CXXFLAGS $CFLAGS" CPPFLAGS="-I/usr/local/include" \
    LDFLAGS="${LDFLAGS} -s" \
    sh -c "./autogen.sh && ./configure ${ConfigOpt} --disable-documentation --with-mbedtls=/usr/local --prefix=${INST_DIR}"

make ${MAKE_FLAGS}
