#!/bin/bash
# Copyright (c) 2000-2012 Synology Inc. All rights reserved.

LANG=C; export LANG
LC_ALL=C; export LC_ALL

case ${MakeClean} in
    [Yy][Ee][Ss])
        make clean
        /bin/rm /usr/local/lib/libmbed.*
        /bin/rm -fr /usr/local/include/mbedtls
        /bin/rm -fr /usr/local/bin/mbedtls_*
        ;;
esac

case ${CleanOnly} in
    [Yy][Ee][Ss])
        return
        ;;
esac

export SHARED=1
# LDFLAGS -s for stripping
env CC="${CC}" CXX="${CXX}" LD="${LD}" AR=${AR} STRIP=${STRIP} RANLIB=${RANLIB} NM=${NM} \
    CFLAGS="${CFLAGS}" CXXFLAGS="$CXXFLAGS $CFLAGS" \
    LDFLAGS="${LDFLAGS} -s" \
    make ${MAKE_FLAGS}

make install
