#!/bin/sh
# checked with: shellcheck -x

# Source package specific variable and functions
SVC_SETUP="$(dirname "$0")/service-setup"
if [ -r "${SVC_SETUP}" ]; then
    #shellcheck source=service-setup
    . "${SVC_SETUP}"
fi

echo "\$config_dir = '$CONFIG_DIR';" >> "$SYNOPKG_PKGDEST/ui/synoenv.php"
echo "\$script_dir = '$SCRIPT_DIR';" >> "$SYNOPKG_PKGDEST/ui/synoenv.php"
echo "\$pid_dir = '$PID_DIR';" >> "$SYNOPKG_PKGDEST/ui/synoenv.php"

conf_files=$(find -L "$CONFIG_DIR" -maxdepth 1 -regextype posix-extended -regex "$CONFFILES_REGEX" -type f -printf '%f ')
if [ -z "$conf_files" ]
then
    echo "Configuration file(s) ss-*.json needs to be created in $CONFIG_DIR" >>"$SYNOPKG_TEMP_LOGFILE"
else
    echo "Using configuration files already existing in $CONFIG_DIR: $conf_files" >>"$SYNOPKG_TEMP_LOGFILE"
fi

exit 0
